[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  HUGO_VERSION = "0.55.2"
  RUBY_VERSION = "2.6.2"
  

[[headers]]
  for = "/*"
  [headers.values]
  Link = "<https://fonts.gstatic.com>; rel=preconnect, </css/main.css>; rel=preload; as=style, </app.js>; rel=preload; as=script"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff2"

[[headers]]
  for = "/"
  [headers.values]
    Link = "</img/facebook-header.jpg>; rel=preload; as=image"

[[headers]]
  for = "/projects/"
  [headers.values]
    Link = "</img/facebook-collage.jpg>; rel=preload; as=image"

[[headers]]
  for = "/values/"
  [headers.values]
    Link = "</img/facebook-classroom.jpg>; rel=preload; as=image"

[[headers]]
  for = "/donate/"
  [headers.values]
    Link = "</img/facebook-cute-girl.jpg>; rel=preload; as=image"