[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  HUGO_VERSION = "0.61.0"

[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = [
  "allow-from https://www.youtube.com/",
  "allow-from https://www.youtube-noocookie.com/",
  "allow-from https://www.facebook.com/"
  ]
  Link = "<https://fonts.gstatic.com>; rel=preconnect, <https://www.facebook.com>; rel=preconnect, </css/main.css>; rel=preload; as=style, </app.js>; rel=preload; as=script"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff2"

[[headers]]
  for = "/"
  [headers.values]
    Link = "</img/facebook-header.webp>; rel=preload; as=image"

[[headers]]
  for = "/projects/"
  [headers.values]
    Link = "</img/facebook-collage.webp>; rel=preload; as=image"

[[headers]]
  for = "/values/"
  [headers.values]
    Link = "</img/facebook-classroom.webp>; rel=preload; as=image"

[[headers]]
  for = "/donate/"
  [headers.values]
    Link = "</img/facebook-cute-girl.webp>; rel=preload; as=image"