[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  HUGO_VERSION = "0.55.2"
  RUBY_VERSION = "2.6.2"
  
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff2"
    Link = <https://fonts.gstatic.com>; rel=preconnect

  for = "/"
  [headers.values]
    Link = </img/facebook-header.jpg>; rel=preload; as=image

  for = "/projects/"
  [headers.values]
    Link = </img/facebook-collage.jpg>; rel=preload; as=image

  for = "/values/"
  [headers.values]
    Link = </img/facebook-classroom.jpg>; rel=preload; as=image

  for = "/donate/"
  [headers.values]
    Link = </img/facebook-cute-girl.jpg>; rel=preload; as=image