[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  HUGO_VERSION = "0.55.1"
  
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff2"
