baseURL = "https://faizeaam.org"
languageCode = "en-us"
googleAnalytics = "UA-114282893-1"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
title = "Faiz-e-Aam Welfare Trust"
enableEmoji = true

[params]
    headline = "Together we can make a difference"
    logo = "https://faizeaam.org/img/apple-touch-icon.png"
    image = "https://faizeaam.org/img/og-image.jpg"
    author = "Ayesha Iqbal"
    facebook = "https://www.facebook.com/Mount-HIRA-Street-Children-School-372062566191109/"

[menu]
    [[menu.main]]
    identifier = "home"
    name = "Home"
    pre = ""
    url = "/"
    weight = -110

    [[menu.main]]
    identifier = "work"
    name = "Projects"
    post = ""
    pre = ""
    url = "/projects/"
    weight = -100

    [[menu.main]]
    identifier = "about"
    name = "Values"
    post = ""
    pre = ""
    url = "/values/"
    weight = -90

    [[menu.main]]
    identifier = "news"
    name = "News"
    post = ""
    pre = ""
    url = "/news/"
    weight = -80

    [[menu.main]]
    identifier = "contact"
    name = "Contact"
    post = ""
    pre = ""
    url = "/contact/"
    weight = -70

    [[menu.main]]
    identifier = "donate"
    name = "Donate"
    post = ""
    pre = ""
    url = "/donate/"
    weight = -70