baseURL = "https://faizeaam.org"
languageCode = "en-us"
googleAnalytics = "UA-114282893-1"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
title = "Faiz-e-Aam Welfare Trust"

[params]
    headline = "Together we can make a difference"
    logo = "https://faizeaam.org/img/apple-touch-icon.png"
    image = "https://faizeaam.org/img/og-image.jpg"
    author = "Ayesha Iqbal"
    facebook = "https://www.facebook.com/Mount-HIRA-Street-Children-School-372062566191109/"